# Generated by Django 5.2.7 on 2025-10-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('data_di_nascita', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fumetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.TextField()),
                ('descrizione', models.TextField()),
                ('anno', models.IntegerField()),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Fumetti.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Capitolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_capitolo', models.TextField(max_length=40)),
                ('numero_pagine_capitolo', models.IntegerField(max_length=120)),
                ('fumetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fumetti.fumetto')),
            ],
        ),
    ]
