# Generated by Django 5.2.7 on 2025-10-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artista',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Capitolo',
            new_name='Chapter',
        ),
        migrations.RenameModel(
            old_name='Fumetto',
            new_name='Manga',
        ),
    ]
