# Generated by Django 5.2.7 on 2025-10-29 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0003_alter_chapter_numero_pagine_capitolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='numero_capitolo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fumetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fumetti.manga')),
            ],
        ),
    ]
