# Generated by Django 5.2.7 on 2025-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0005_manga_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='numero_capitolo',
            field=models.IntegerField(blank=True),
        ),
    ]
