# Generated by Django 5.2.7 on 2025-10-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0011_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
