# Generated by Django 5.2.7 on 2025-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0002_rename_artista_artist_rename_capitolo_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='numero_pagine_capitolo',
            field=models.IntegerField(),
        ),
    ]
