# Generated by Django 5.2.7 on 2025-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0004_chapter_numero_capitolo_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='img_url',
            field=models.TextField(blank=True),
        ),
    ]
