# Generated by Django 5.2.7 on 2025-10-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0006_alter_chapter_numero_capitolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab_Generi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_genere', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='genere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fumetti.tab_generi'),
        ),
    ]
