# Generated by Django 5.2.7 on 2025-10-30 08:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0007_tab_generi_manga_genere'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='fumetto',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='numero_capitolo',
        ),
        migrations.AddField(
            model_name='chapter',
            name='data_pubblicazione_capitolo',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Fumetti.volume'),
            preserve_default=False,
        ),
    ]
