# Generated by Django 5.2.7 on 2025-10-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0008_user_remove_chapter_fumetto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fumetti.volume'),
        ),
    ]
