# Generated by Django 5.2.7 on 2025-10-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0010_alter_chapter_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='standard', max_length=10),
        ),
    ]
