# Generated by Django 5.2.7 on 2025-10-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0012_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='standard', max_length=10)),
            ],
        ),
    ]
