# Generated by Django 5.2.7 on 2025-11-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0013_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab_valutazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert', models.IntegerField(default=0)),
                ('media', models.FloatField(default=0.0)),
                ('manga_riferimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fumetti.manga')),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
