# Generated by Django 5.2.7 on 2025-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0014_tab_valutazioni_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_valutazioni',
            name='somma_stelle',
            field=models.IntegerField(default=0),
        ),
    ]
