# Generated by Django 5.2.7 on 2025-11-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fumetti', '0016_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manga_letti',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
